on:
  push:
    tags:
      - "v*"
  watch:
    types: started

name: CI
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: goreleaser
        uses: docker://goreleaser/goreleaser:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: release --config .github/goreleaser.yml
        if: success()
